---
- name: Run database container
  community.docker.docker_container:
    name: postgrestp1
    image: ky0u/postgrestp1:1.0
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ POSTGRES_DB }}"
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
    volumes:
      - db-data:/var/lib/postgresql/data
