---
- name: Run database container
  community.docker.docker_container:
    name: postgrestp1
    image: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}/tp-devops-database:latest"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ POSTGRES_DB }}"
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - db-data:/var/lib/postgresql/data
