all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /opt/docker_venv/bin/python3
    POSTGRES_DB: "{{ vault_postgres_db }}"
    POSTGRES_USER: "{{ vault_postgres_user }}"
    POSTGRES_PASSWORD: "{{ vault_postgres_password }}"
  children:
    prod:
      hosts: 52.31.119.148
