---
- name: Run backend app container
  community.docker.docker_container:
    name: simplestudentapi
    image: ky0u/simplestudentapi:1.0
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-network
