---
- name: Run backend app container
  community.docker.docker_container:
    name: simplestudentapi
    image: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}/tp-devops-simple-api:latest"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-network
    env:
      DATABASE_HOST: postgrestp1
