---
- name: Run proxy container
  community.docker.docker_container:
    name: httpd
    image: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}/tp-devops-httpd:latest"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-network
    ports:
      - "80:80"
