name: CI devops 2025
on:
  # lance les tests sur main et develop à chaque push
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    #les tests vont run sur une vm ubuntu
    runs-on: ubuntu-24.04
    steps:
      #récupère le code du repository avec une actions built in par github action
      - uses: actions/checkout@v4

      #installe java 21 (avec une pre-built action)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      #dernier step qui build et lance les tests
      - name: Build and test with Maven
        run: mvn clean verify --file simple-api/pom.xml

      # lance une analyse sonarCloud pour tester la securité, le coverage et les bugs
      # SONAR_TOKEN est stocké sur github
      - name: SonarCloud analysis
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=youk-03_tp-devops-correction-docker -Dsonar.organization=youk-03 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./simple-api/pom.xml
